### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by ivasilov** [pmowrer/semantic-release-plugin-decorators#10]
Based on this [comment](https://github.com/Updater/semantic-release-plugin-decorators/pull/9#issuecomment-485490685) it seems like this project (and semantic-release-monorepo) to be abandoned.

Would you be willing to transfer ownership of the npm package (and semantic-release-monorepo) so that we can continue maintaining?

**Comment by pmowrer** [comment]
Thanks for offering to help @ivasilov! I'll be maintaining the project from now on but would love any help I can get if you're still interested.
