### ISSUE TITLE
Support For New Semantic Release Version and Node 18

### ISSUE THREAD

**Issue by w4rlock** [pmowrer/semantic-release-plugin-decorators#32]
Hi @pmowrer 

I created a new pull request.
This plugin doesn't work in last semantic release for node 18. 
also i have changes on "semantic-release-monorepo" for support last version.

Please i need merge theses changes.. 
https://github.com/pmowrer/semantic-release-plugin-decorators/pull/31

**Comment by joshualang** [comment]
+1 It would be great if this package moves to es modules. thank you for your work @w4rlock

**Comment by karlo-humanmanaged** [comment]
I hope this gets noticed. This will also allow me to use semantic-release/gitlab v10

**Comment by drochetti** [comment]
+1 I've been trying to use semantic-release in my NX workspace through [TheUnderScorer/nx-semantic-release](https://github.com/TheUnderScorer/nx-semantic-release) but the lack os ESM support from the plugin decorators is a blocker. I'd love to see this through and I am willing to provide help if necessary.

**Comment by tjg184** [comment]
Not sure if this helps, but this is how we worked around the issue. I have tested with node >= 18 as well as older versions. 
https://github.com/tjg184/semantic-release-plugin-decorators/tree/fix/dynamic_import
