### ISSUE TITLE
v1.2.2 breaks publishing when using semantic-release-monorepo

### ISSUE THREAD

**Issue by constantology** [pmowrer/semantic-release-plugin-decorators#5]
Hello,

We use `lerna`, `semantic-release` and `semantic-release-monorepo` to version and publish our projects' shared modules.

The change that triggered `semantic-release-plugin-decorators@v1.2.2` has broken our pipeline. 

This is because in order to use `semantic-release-monorepo` you need to put your `analyzeCommits` and `generateNotes` configurations inside a `monorepo` Object of your `release` configuration. 
See the [semantic-release-monorepo: Example of use with non-default set of plugins](/Updater/semantic-release-monorepo#example-of-use-with-non-default-set-of-plugins) for an example of this.

If we include an `release.analyzeCommits` configuration, then `semantic-release-monorepo` does not execute at all. If we put it inside a `monorepo` Object, as outlined above, then it is now ignored because of the change in `semantic-release-plugin-decorators@v1.2.2` and as such, neither out `preset: eslint`, nor our custom `releaseRules: Object` get picked up by `semantic-release-monorepo`, which then prevents `semantic-release` from versioning and publishing, as it can't find any valid changes.

I'm unsure if this will also affect other plugins which use `semantic-release-plugin-decorators`, however, I will also file this issue in the `semantic-release-monorepo` repository.

For now, we've hard versioned `semantic-release-plugin-decorators` to `v1.2.1`, at the same time, it would be nice to not be locked into this version to be able to receive future updates. 🙂

Thanks,
Christos.

**Comment by pmowrer** [comment]
Thanks for the report @constantology! This should be fixed with [`1.2.3`](https://github.com/Updater/semantic-release-plugin-decorators/releases/tag/v1.2.3)
